services:
  web-service:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - model-service
    image: kohleivo/djl-serving-consumer:latest
    ports:
      - "80:8082"
    restart: always
    environment:
      - DJL_SERVING_MODEL_NAME=traced_resnet18

  model-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: kohleivo/djl-serving:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVING_RESERVED_MEMORY_MB=64
      - SERVING_REQUIRED_MEMORY_MB=64
      - SERVING_MIN_WORKERS=1
      - SERVING_MAX_WORKERS=1
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - JAVA_OPTS=-Xms64m -Xmx256m -XX:MaxMetaspaceSize=96m
